### ISSUE TITLE
Add iQIYI, Bili.Copilot, LyricEase, HyPlayer and HotLyric

### ISSUE THREAD

**Issue by FrzMtrsprt** [DesignLipsx/WinUI-3-Apps-List#12]
iQIYI is iQIYI's official WinUI 3 client, [Microsoft Store](https://www.microsoft.com/store/productId/9NBLGGH5WXNW)

Bili.Copilot is Bilibili's third party client, [GitHub](https://github.com/Richasy/Bili.Copilot), [Microsoft Store](https://www.microsoft.com/store/apps/9MVFJLPH517M)

LyricEase is Netease Music's third party client, [App Center](https://install.appcenter.ms/users/brandonw3612/apps/lyricease/distribution_groups/public) (it was removed from Microsoft Store due to copyright issues, and it's closed source, so App Center is currently the only way to download)

HyPlayer is Netease Music's third party client, [GitHub](https://github.com/HyPlayer/HyPlayer) (it was removed from Microsoft Store for the same reason)

HotLyric provides desktop lyrics for LyricEase and HyPlayer, [GitHub](https://github.com/cnbluefire/HotLyric), [Microsoft Store](https://www.microsoft.com/store/productId/9MXFFHVQVBV9)

**Comment by KParthSingh** [comment]
why they all are in Chinese??

**Comment by FrzMtrsprt** [comment]
...Because they are all Chinese apps.

**Comment by Jishnu-jithu** [comment]
All apps added to the list.

**Comment by FrzMtrsprt** [comment]
Okay, thanks!
