### ISSUE TITLE
Guys, I found a treasure!

### ISSUE THREAD

**Issue by pdimu** [DesignLipsx/WinUI-3-Apps-List#26]
I was browsing the Fluent Store app and discovered a "bundle" named Launch 2020 from UWP Community. Ok, you'll blame me, but UWP is really similar to WinUI 3, and it's worth to look after its apps: [try to discover more, this is the main link](https://uwpcommunity.com/launch/)

**Comment by DesignLipsx** [comment]
Added to the list
