### ISSUE TITLE
MyNotes app reminder feature

### ISSUE THREAD

**Issue by ErenCanUtku** [DesignLipsx/WinUI-3-Apps-List#7]
[MyNotes](https://github.com/ErenCanUtku/MyNotes) app also have a reminders feature that uses windows notifications just like [this one](https://apps.microsoft.com/detail/9MW5VRL0BQT9?hl=en-us&gl=US). If it's possible, can you add it under reminders section too?
![image_2023-12-18_192208249](https://github.com/DesignLipsx/WinUI-3-Apps-List/assets/47883186/b7d2ec37-6f4e-49b5-ab22-db73e90150c9)

**Comment by Jishnu-jithu** [comment]
I initially thought MyNotes was more of a note-taking app, I'll make sure to add MyNotes to the Reminders section as well. Thanks for bringing it to my attention!
