### ISSUE TITLE
ATube - YT App is now a paid software

### ISSUE THREAD

**Issue by KParthSingh** [DesignLipsx/WinUI-3-Apps-List#8]
your welcome.

**Comment by Jishnu-jithu** [comment]
Thank you for the update! I'll make the change.

**Comment by KParthSingh** [comment]
also i think text space is removed from the store

**Comment by Jishnu-jithu** [comment]
It seems the [text space](https://apps.microsoft.com/detail/9N6CPGZGXSVT) is back on the Microsoft Store.

**Comment by KParthSingh** [comment]
for some reason in my pc it doesnt show ratings total download and install button

**Comment by Jishnu-jithu** [comment]
in my pc it shown the download button yesterday, but now its gone. i removed it from the list.

**Comment by KParthSingh** [comment]
any idea whats happening?
